name: RunsafeJail
main: no.runsafe.runsafejail.Plugin
version: 1.0
authors: [Kruithne]
depend: []
description: A plugin for jailing players in preset locations.
commands:
  jail:
    description: Jails a player at a certain jail
    usage: /jail <player> [jail] <time>
  unjail:
    description: Unjails a player, returning them to their previous location.
    usage: /unjail <player>